### ISSUE TITLE
Using plugin for Amazon RDS

### ISSUE THREAD

**Issue by ghost** [nmcquay/shard_id_udf#1]
Hi, I am using Amazon RDS. How can I add .so file in there. Is there any way to write these function using SQL procedure or function instead of c plugin.

**Comment by nmcquay** [comment]
I have not used RDS, so I don't know what is possible there. If you do not have access to install new software on the db server, then I doubt you'll be able to install a UDF.

MySQL does not have a time function that returns milliseconds. The id's generated by this projects UDF depend on milliseconds. You can do roughly the same thing using seconds (UNIX_TIMESTAMP) and a flickr style Ticketing table like:

``` sql
CREATE TABLE Tickets64 (
    `id` bigint(20) unsigned NOT NULL auto_increment,
    `stub` char(1) NOT NULL default '',
    PRIMARY KEY (`id`),
    UNIQUE KEY `stub` (`stub`)
) ENGINE=MyISAM;

DELIMITER $$

DROP FUNCTION IF EXISTS generate_shard_id$$
DROP FUNCTION IF EXISTS shard_id_to_utc$$

CREATE FUNCTION generate_shard_id( shard INT )
RETURNS BIGINT UNSIGNED NOT DETERMINISTIC
MODIFIES SQL DATA
BEGIN
    DECLARE seq_mask INT;
    DECLARE seq_id BIGINT;
    DECLARE now INT;
    DECLARE internal_epoch INT;
    DECLARE retval BIGINT;

    SET seq_mask = 4095;
    SET internal_epoch = 1370070000;
    REPLACE INTO Tickets64 (stub) VALUES ('a');
    SET seq_id = LAST_INSERT_ID() & seq_mask;
    SET retval = (UNIX_TIMESTAMP() - internal_epoch) << 32 | seq_id << 20 | shard;
    RETURN retval;
END
$$

CREATE FUNCTION shard_id_to_utc( id BIGINT )
RETURNS BIGINT UNSIGNED DETERMINISTIC
BEGIN
    DECLARE internal_epoch INT;
    SET internal_epoch = 1370070000;
    RETURN (id >> 32) + internal_epoch;
END
$$

DELIMITER ;
```

I don't know how correct the above is, but it should be close to correct. The upper 32-bits should be the unix timestamp. The middle 12-bits are an auto-increment value to prevent collisions on the same shard for the same second. The lower 20-bits are the shard the id was generated for, and you have to pass it in ahead of time. You can shift the bit allocations around to whatever makes sense for your setup.

There might be a way to get rid of the Tickets64 table, but I'm not sure how off the top of my head. The Tickets64 table provides us with a counter that will be shared across sessions and will be unique to each virtual shard.

You can also bake the shard into each generate_shard_id function per virtual shard, so that you don't need to pass it around.
